<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'iPhone 15 Pro Max',
                'slug' => 'iphone-15-pro-max',
                'description' => 'iPhone 15 Pro Max. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
                'features' => 'Strong and light titanium design|A17 Pro chip with 6-core GPU|48MP Main camera with 5x Telephoto|Customizable Action button|All-day battery life',
                'specifications' => json_encode([
                    'Display' => '6.7-inch Super Retina XDR display',
                    'Chip' => 'A17 Pro chip',
                    'Camera' => '48MP Main | 12MP Ultra Wide | 12MP Telephoto 5x',
                    'Storage' => '256GB',
                    'Battery' => 'Up to 29 hours video playback',
                    'Material' => 'Titanium',
                ]),
                'price' => 145000,
                'original_price' => 155000,
                'sku' => 'IP15PM256',
                'stock' => 15,
                'image' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500',
                    'https://images.unsplash.com/photo-1695048133143-b7c4f8f2b3e5?w=500',
                    'https://images.unsplash.com/photo-1697834926904-7e3f033a36d3?w=500',
                    'https://images.unsplash.com/photo-1678685888221-cda16c1a7e1e?w=500',
                ]),
                'category_id' => 1,
                'brand_id' => 1,
                'is_featured' => true,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'description' => 'Meet Galaxy S24 Ultra, the ultimate form of Galaxy Ultra with a new titanium exterior and a 17.25cm (6.8") flat display. It\'s an absolute marvel of design.',
                'features' => '200MP camera with AI Zoom|Built-in S Pen|Snapdragon 8 Gen 3|Dynamic AMOLED 2X display|All-day intelligent battery',
                'specifications' => json_encode([
                    'Display' => '6.8-inch Dynamic AMOLED 2X',
                    'Processor' => 'Snapdragon 8 Gen 3',
                    'Camera' => '200MP Wide | 12MP Ultra Wide | 10MP Telephoto',
                    'RAM' => '12GB',
                    'Storage' => '256GB',
                    'Battery' => '5000mAh',
                ]),
                'price' => 125000,
                'original_price' => 135000,
                'sku' => 'SGS24U256',
                'stock' => 20,
                'image' => 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500',
                    'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500',
                    'https://images.unsplash.com/photo-1591122947157-26bad3a117d2?w=500',
                    'https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=500',
                ]),
                'category_id' => 1,
                'brand_id' => 2,
                'is_featured' => true,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'name' => 'MacBook Pro 14" M3',
                'slug' => 'macbook-pro-14-m3',
                'description' => 'MacBook Pro blasts forward with the M3 chip. With best-in-class battery life and a beautiful Liquid Retina XDR display, it\'s a pro laptop without equal.',
                'features' => 'M3 chip for incredible performance|14.2-inch Liquid Retina XDR display|Up to 22 hours battery life|1080p FaceTime HD camera|Six-speaker sound system',
                'specifications' => json_encode([
                    'Chip' => 'Apple M3',
                    'Display' => '14.2-inch Liquid Retina XDR',
                    'Memory' => '8GB unified memory',
                    'Storage' => '512GB SSD',
                    'Battery' => 'Up to 22 hours',
                    'Ports' => '3x Thunderbolt 4, HDMI, SD card',
                ]),
                'price' => 235000,
                'original_price' => 245000,
                'sku' => 'MBP14M3',
                'stock' => 8,
                'image' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500',
                    'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=500',
                    'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500',
                ]),
                'category_id' => 2,
                'brand_id' => 1,
                'is_featured' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'name' => 'iPad Air M2',
                'slug' => 'ipad-air-m2',
                'description' => 'iPad Air. With an immersive 11-inch Liquid Retina display. The amazingly fast M2 chip. Works with Apple Pencil Pro and Magic Keyboard. And supports Wi‑Fi 6E.',
                'features' => 'M2 chip with 8-core CPU|11-inch Liquid Retina display|Works with Apple Pencil Pro|12MP Wide camera|All-day battery life',
                'specifications' => json_encode([
                    'Chip' => 'Apple M2',
                    'Display' => '11-inch Liquid Retina',
                    'Storage' => '128GB',
                    'Camera' => '12MP Wide, 12MP Ultra Wide front',
                    'Battery' => 'Up to 10 hours',
                    'Connectivity' => 'Wi-Fi 6E',
                ]),
                'price' => 75000,
                'original_price' => 82000,
                'sku' => 'IPADAIRM2',
                'stock' => 25,
                'image' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500',
                    'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=500',
                    'https://images.unsplash.com/photo-1585790050230-5dd28404f379?w=500',
                ]),
                'category_id' => 3,
                'brand_id' => 1,
                'is_featured' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'name' => 'AirPods Pro 2nd Gen',
                'slug' => 'airpods-pro-2nd-gen',
                'description' => 'AirPods Pro feature up to 2x more Active Noise Cancellation, plus Adaptive Transparency, and Personalized Spatial Audio with dynamic head tracking for immersive sound.',
                'features' => 'Active Noise Cancellation|Adaptive Transparency|Personalized Spatial Audio|Up to 6 hours listening time|MagSafe Charging Case',
                'specifications' => json_encode([
                    'Chip' => 'H2 chip',
                    'Active Noise Cancellation' => 'Yes',
                    'Battery' => 'Up to 6 hours',
                    'Case Battery' => 'Up to 30 hours total',
                    'Charging' => 'MagSafe, USB-C',
                    'Dust & Water Resistant' => 'IP54',
                ]),
                'price' => 28000,
                'original_price' => 32000,
                'sku' => 'APP2G',
                'stock' => 40,
                'image' => 'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=500',
                    'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=500',
                    'https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=500',
                ]),
                'category_id' => 5,
                'brand_id' => 1,
                'is_featured' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Apple Watch Series 9',
                'slug' => 'apple-watch-series-9',
                'description' => 'Smarter. Brighter. Mightier. The S9 chip enables a super-bright display and a magical new way to quickly and easily interact with your Apple Watch without touching the screen.',
                'features' => 'S9 SiP for faster performance|Always-On Retina display|Blood Oxygen app|ECG app|Advanced workout metrics',
                'specifications' => json_encode([
                    'Chip' => 'S9 SiP',
                    'Display' => 'Always-On Retina LTPO OLED',
                    'Case Size' => '45mm',
                    'Water Resistant' => '50 meters',
                    'Battery' => 'Up to 18 hours',
                    'Health Features' => 'ECG, Blood Oxygen, Heart Rate',
                ]),
                'price' => 45000,
                'original_price' => 48000,
                'sku' => 'AWS9',
                'stock' => 18,
                'image' => 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=500',
                    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500',
                    'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=500',
                ]),
                'category_id' => 4,
                'brand_id' => 1,
                'is_featured' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Samsung Galaxy Tab S9',
                'slug' => 'samsung-galaxy-tab-s9',
                'description' => 'Galaxy Tab S9 is a premium Android tablet with a stunning 11-inch display, powerful performance, and an included S Pen for creativity and productivity.',
                'features' => 'Dynamic AMOLED 2X display|Snapdragon 8 Gen 2|S Pen included|IP68 water resistance|All-day battery',
                'specifications' => json_encode([
                    'Display' => '11-inch Dynamic AMOLED 2X',
                    'Processor' => 'Snapdragon 8 Gen 2',
                    'RAM' => '8GB',
                    'Storage' => '128GB',
                    'Battery' => '8,400mAh',
                    'S Pen' => 'Included',
                ]),
                'price' => 65000,
                'original_price' => 70000,
                'sku' => 'SGTS9',
                'stock' => 12,
                'image' => 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=500',
                    'https://images.unsplash.com/photo-1585790050230-5dd28404f379?w=500',
                    'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500',
                ]),
                'category_id' => 3,
                'brand_id' => 2,
                'is_featured' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'description' => 'Google Pixel 8 Pro is Google\'s smartest phone yet, with the new Google Tensor G3 chip that\'s custom-designed to keep up with your life.',
                'features' => 'Google Tensor G3 chip|50MP camera with AI|7 years of updates|Magic Eraser|Best Take',
                'specifications' => json_encode([
                    'Chip' => 'Google Tensor G3',
                    'Display' => '6.7-inch LTPO OLED 120Hz',
                    'Camera' => '50MP Main | 48MP Ultra Wide | 48MP Telephoto',
                    'RAM' => '12GB',
                    'Storage' => '256GB',
                    'Battery' => '5,050mAh',
                ]),
                'price' => 95000,
                'original_price' => 105000,
                'sku' => 'GP8P',
                'stock' => 14,
                'image' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500',
                    'https://images.unsplash.com/photo-1598327105854-f4c90e6c11c8?w=500',
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500',
                ]),
                'category_id' => 1,
                'brand_id' => 5,
                'is_featured' => true,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Dell XPS 13',
                'slug' => 'dell-xps-13',
                'description' => 'The Dell XPS 13 is a premium ultrabook featuring a stunning InfinityEdge display, powerful Intel processors, and exceptional build quality.',
                'features' => 'Intel Core i7 processor|13.4-inch FHD+ display|16GB RAM|512GB SSD|All-day battery life',
                'specifications' => json_encode([
                    'Processor' => 'Intel Core i7-1360P',
                    'Display' => '13.4-inch FHD+ InfinityEdge',
                    'RAM' => '16GB LPDDR5',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'Intel Iris Xe',
                    'Battery' => 'Up to 12 hours',
                ]),
                'price' => 135000,
                'original_price' => 145000,
                'sku' => 'DELLXPS13',
                'stock' => 10,
                'image' => 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500',
                    'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500',
                    'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=500',
                ]),
                'category_id' => 2,
                'brand_id' => 7,
                'is_featured' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Sony WH-1000XM5',
                'slug' => 'sony-wh-1000xm5',
                'description' => 'Industry-leading noise cancellation with the new Auto NC Optimizer, exceptional sound quality, crystal clear hands-free calling, and up to 30 hours battery life.',
                'features' => 'Industry-leading noise cancellation|30 hours battery life|Multipoint connection|Speak-to-Chat|Premium sound quality',
                'specifications' => json_encode([
                    'Driver Unit' => '30mm',
                    'Noise Cancellation' => 'Yes, HD NC Processor QN1',
                    'Battery Life' => 'Up to 30 hours',
                    'Charging' => 'USB-C quick charging',
                    'Connectivity' => 'Bluetooth 5.2',
                    'Weight' => '250g',
                ]),
                'price' => 35000,
                'original_price' => 39000,
                'sku' => 'SONYWH1000XM5',
                'stock' => 22,
                'image' => 'https://images.unsplash.com/photo-1545127398-14699f92334b?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1545127398-14699f92334b?w=500',
                    'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcf?w=500',
                    'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500',
                ]),
                'category_id' => 5,
                'brand_id' => 6,
                'is_featured' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'name' => 'OnePlus 12',
                'slug' => 'oneplus-12',
                'description' => 'OnePlus 12 features the latest Snapdragon 8 Gen 3, a stunning 120Hz AMOLED display, and blazing-fast 100W SUPERVOOC charging.',
                'features' => 'Snapdragon 8 Gen 3|50MP Hasselblad camera|100W fast charging|120Hz AMOLED display|Up to 16GB RAM',
                'specifications' => json_encode([
                    'Processor' => 'Snapdragon 8 Gen 3',
                    'Display' => '6.82-inch AMOLED 120Hz',
                    'Camera' => '50MP Main | 48MP Ultra Wide | 64MP Telephoto',
                    'RAM' => '12GB',
                    'Storage' => '256GB',
                    'Battery' => '5,400mAh with 100W charging',
                ]),
                'price' => 78000,
                'original_price' => 85000,
                'sku' => 'OP12',
                'stock' => 16,
                'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500',
                    'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=500',
                    'https://images.unsplash.com/photo-1581993192008-63e896f4f744?w=500',
                ]),
                'category_id' => 1,
                'brand_id' => 4,
                'is_featured' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Xiaomi 13 Pro',
                'slug' => 'xiaomi-13-pro',
                'description' => 'Xiaomi 13 Pro features Leica professional optics, Snapdragon 8 Gen 2, and a stunning 6.73" AMOLED display with Dolby Vision.',
                'features' => 'Leica professional optics|Snapdragon 8 Gen 2|120W HyperCharge|120Hz AMOLED display|IP68 water resistance',
                'specifications' => json_encode([
                    'Processor' => 'Snapdragon 8 Gen 2',
                    'Display' => '6.73-inch AMOLED 120Hz',
                    'Camera' => '50MP Leica Main | 50MP Ultra Wide | 50MP Telephoto',
                    'RAM' => '12GB',
                    'Storage' => '256GB',
                    'Battery' => '4,820mAh with 120W charging',
                ]),
                'price' => 72000,
                'original_price' => 79000,
                'sku' => 'XM13PRO',
                'stock' => 19,
                'image' => 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=500',
                'images' => json_encode([
                    'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=500',
                    'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=500',
                    'https://images.unsplash.com/photo-1592286927405-2a5a16c08181?w=500',
                ]),
                'category_id' => 1,
                'brand_id' => 3,
                'is_featured' => false,
                'is_new' => false,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
